using FluentValidation;

namespace Siri.Modules.Learning.Application;

/// <summary>Request payload for POST /api/learning/admin/certificates (ops/backfill/reissue — see
/// <c>CertificateEndpoints</c>'s own doc comment for why this is admin-facing). Deliberately has no
/// <c>SerialNo</c>/<c>VerifyCode</c> fields — both are server-generated by <see cref="CertificateService"/>
/// before calling <see cref="Domain.CERTIFICATE.Create"/>, never client-supplied (same "server decides the
/// opaque identifier, client never does" reasoning <c>Siri.Modules.Catalog</c>'s slug generation already
/// establishes for course slugs). Records/DTOs in this module are NOT uppercased — see
/// <see cref="IEnrollmentRepository"/>'s own doc comment for the naming-exception reasoning.</summary>
public sealed record IssueCertificateCommand(Guid EnrollmentId, string? PdfStorageKey);

public sealed record CertificateResponse(
    Guid Id,
    Guid EnrollmentId,
    string SerialNo,
    string VerifyCode,
    DateTime IssuedAtUtc,
    string? PdfStorageKey,
    DateTime? RevokedAtUtc);

public sealed record CertificateDetailResponse(
    Guid Id,
    Guid EnrollmentId,
    string SerialNo,
    string VerifyCode,
    DateTime IssuedAtUtc,
    string? PdfStorageKey,
    DateTime? RevokedAtUtc,
    string LearnerName,
    string CourseTitle,
    string VerifyUrl);

/// <summary>Shape returned by the public, <c>AllowAnonymous</c> verify-by-code endpoint.</summary>
public sealed record CertificateVerificationResponse(
    string SerialNo,
    string VerifyCode,
    DateTime IssuedAtUtc,
    bool IsValid,
    DateTime? RevokedAtUtc,
    string? LearnerName,
    string? CourseTitle);

/// <summary>Format-only checks — no DB access (see <c>CreateEnrollmentValidator</c>'s own doc comment for
/// this module's format-vs-business-rule split).</summary>
public sealed class IssueCertificateValidator : AbstractValidator<IssueCertificateCommand>
{
    public IssueCertificateValidator()
    {
        RuleFor(c => c.EnrollmentId).NotEmpty();
        RuleFor(c => c.PdfStorageKey).MaximumLength(500);
    }
}
