using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Siri.Modules.Catalog.Domain;
using Siri.Persistence;

namespace Siri.UnitTests.Persistence;

/// <summary>
/// Every Guid primary key is generated by the application (<c>UuidV7.NewId()</c>), never by the store. Under EF Core's default
/// (<c>ValueGenerated.OnAdd</c> for a Guid key) a child that already carries its key and is reached through a TRACKED parent's
/// navigation collection — <c>quiz.AddQuestion(...)</c>, <c>course.AddLiveSession(...)</c> — is assumed to exist and is tracked as
/// Modified: <c>SaveChanges</c> then issues an UPDATE that matches no row and throws <see cref="DbUpdateConcurrencyException"/>.
/// This was a real production defect found by the integration suite (instructors could not add quiz questions or live sessions);
/// <c>ModelBuilderExtensions.ApplyClientGeneratedGuidKeys</c> is the fix and these tests pin it. No database is touched.
/// </summary>
public class ClientGeneratedGuidKeyConventionTests
{
    private static AppDbContext CreateContext()
    {
        // AppDbContext discovers its entity configurations from the Siri.Modules.* assemblies that are LOADED; make sure all are.
        foreach (var path in Directory.EnumerateFiles(AppContext.BaseDirectory, "Siri.Modules.*.dll"))
        {
            Assembly.LoadFrom(path);
        }

        return new AppDbContext(new DbContextOptionsBuilder<AppDbContext>()
            .UseNpgsql("Host=localhost;Port=1;Database=unit-test;Username=none;Password=none")
            .Options);
    }

    [Fact]
    public void Model_EverySingleColumnGuidPrimaryKey_IsNeverStoreGenerated()
    {
        using var context = CreateContext();

        var offenders = context.Model.GetEntityTypes()
            .Select(entityType => (entityType, key: entityType.FindPrimaryKey()))
            .Where(x => x.key is { Properties.Count: 1 } && x.key.Properties[0].ClrType == typeof(Guid))
            .Where(x => x.key!.Properties[0].ValueGenerated != ValueGenerated.Never)
            .Select(x => x.entityType.DisplayName())
            .ToList();

        Assert.Empty(offenders);
    }

    [Fact]
    public void DetectChanges_ChildAddedToTrackedParent_IsTrackedAsAddedNotModified()
    {
        using var context = CreateContext();
        var course = COURSE.Create(
            slug: "guid-key-convention",
            title: "Guid key convention",
            instructorId: Guid.CreateVersion7(),
            categoryId: Guid.CreateVersion7(),
            level: CourseLevel.Beginner,
            language: CourseLanguage.Thai,
            price: 990m);
        context.Attach(course); // the parent is already "loaded": Unchanged, no sections yet

        var section = course.AddSection("Section 1");
        context.ChangeTracker.DetectChanges();

        Assert.Equal(EntityState.Added, context.Entry(section).State);
    }
}
