using Siri.Persistence.Conventions;
using Siri.SharedKernel;

namespace Siri.Modules.Learning.Domain;

/// <summary>
/// A certificate of completion issued for one finished <see cref="ENROLLMENT"/> — docs/DATABASE.md's
/// "learning" section: "Certificates(Id PK, EnrollmentId FK UQ, SerialNo UQ, VerifyCode UQ, IssuedAtUtc,
/// PdfStorageKey, RevokedAtUtc)". One certificate per enrollment, ever (<see cref="ENROLLMENT_ID"/> is
/// unique — see <c>CertificateConfiguration</c>).
/// <para>
/// <b>QR-on-certificate (docs/DECISIONS.md D-16's SiriLearn-spec-reconciliation delta, P5-03) needs NO
/// schema change</b> — it is a render-time concern layered over <see cref="VERIFY_CODE"/> and a public
/// verify URL (<c>GET /api/learning/certificates/verify/{verifyCode}</c>, see
/// <c>CertificateEndpoints.MapCertificateEndpoints</c>), not a new column. A later task generates the QR
/// image (most likely encoding that same verify URL) at PDF-render time; nothing here needs to store the
/// QR itself.
/// </para>
/// <para>
/// <see cref="SERIAL_NO"/> and <see cref="VERIFY_CODE"/> are two different things despite both being
/// unique opaque strings: <see cref="SERIAL_NO"/> is a human-facing, likely sequential/structured
/// identifier printed on the certificate itself (e.g. an ordinal per year); <see cref="VERIFY_CODE"/> is
/// the (harder to guess, unstructured) secret-ish token used for the public lookup endpoint — keeping them
/// separate means a certificate's visible serial number never has to be guessable-resistant on its own.
/// Both are generated by the Service layer before calling <see cref="Create"/> (this aggregate does not
/// invent its own identifiers/business values, same "caller decides, aggregate just stores" split
/// <c>QUIZ_ATTEMPT.Start</c>'s <c>attemptNo</c> parameter already establishes) — exactly how is a later
/// task's decision, not this scaffold's.
/// </para>
/// <para>
/// <b>UPPERCASE naming exception</b> — see <see cref="ENROLLMENT"/>'s own doc comment for the full
/// reasoning (this entity implements <see cref="IAuditable"/>, so its four properties stay PascalCase in
/// C# the same way).
/// </para>
/// <para>
/// <b>No hard delete (this entity — CLAUDE.md's ground rule #5 names "Certificates" explicitly by name,
/// alongside Orders/Payments/RevenueSplits/Enrollments):</b> there is no delete method here, and never will
/// be — a certificate is invalidated via <see cref="Revoke"/> (sets <see cref="REVOKED_AT_UTC"/>), which a
/// public verify lookup then reports as not valid, never by removing the row. <see cref="ENROLLMENT_ID"/>
/// gets a real FK to <see cref="ENROLLMENT"/> (same module/schema, both sides built in this exact scaffold
/// pass) but stays <c>NoAction</c>, not <c>Cascade</c> — see <see cref="EPISODE_PROGRESS"/>'s own doc
/// comment for the direct contrast between the two (a progress row is a meaningless composition child with
/// no life of its own; a certificate is exactly the kind of durable, individually-significant financial/
/// entitlement-adjacent record ground rule #5 exists to protect).
/// </para>
/// <para>
/// This is a SCAFFOLD pass — see <see cref="ENROLLMENT"/>'s own doc comment for what that means for method
/// bodies here.
/// </para>
/// </summary>
public sealed class CERTIFICATE : IAuditable
{
    /// <summary>EF Core materialization only.</summary>
    private CERTIFICATE()
    {
    }

    public Guid CERTIFICATE_ID { get; private set; }

    /// <summary>FK to <see cref="ENROLLMENT.ENROLLMENT_ID"/>, unique — see this class's own doc comment for
    /// why this stays <c>NoAction</c> rather than the <c>Cascade</c> <see cref="EPISODE_PROGRESS"/> uses for
    /// the same kind of same-module reference.</summary>
    public Guid ENROLLMENT_ID { get; private set; }

    /// <summary>Human-facing printed identifier — see this class's own doc comment for how this differs
    /// from <see cref="VERIFY_CODE"/>.</summary>
    public string SERIAL_NO { get; private set; } = string.Empty;

    /// <summary>Opaque token used by the public verify endpoint — see this class's own doc comment.
    /// </summary>
    public string VERIFY_CODE { get; private set; } = string.Empty;

    public DateTime ISSUED_AT_UTC { get; private set; }

    /// <summary>Object-storage key for the rendered PDF — <c>null</c> until a later task's PDF-rendering
    /// step fills it in (this scaffold pass has no file-generation logic, matching every other
    /// not-yet-built storage-producing step in this codebase, e.g. <c>media.MediaAssets</c> for Bunny
    /// Stream uploads).</summary>
    public string? PDF_STORAGE_KEY { get; private set; }

    /// <summary><c>null</c> while valid. Once set, the public verify endpoint reports this certificate as
    /// no longer valid — see <see cref="Revoke"/>.</summary>
    public DateTime? REVOKED_AT_UTC { get; private set; }

    // ---- IAuditable (stays PascalCase — see ENROLLMENT's own doc comment) -------------------------
    public DateTime CreatedAtUtc { get; private set; }

    public Guid? CreatedBy { get; private set; }

    public DateTime? UpdatedAtUtc { get; private set; }

    public Guid? UpdatedBy { get; private set; }

    DateTime IAuditable.CreatedAtUtc
    {
        get => CreatedAtUtc;
        set => CreatedAtUtc = value;
    }

    Guid? IAuditable.CreatedBy
    {
        get => CreatedBy;
        set => CreatedBy = value;
    }

    DateTime? IAuditable.UpdatedAtUtc
    {
        get => UpdatedAtUtc;
        set => UpdatedAtUtc = value;
    }

    Guid? IAuditable.UpdatedBy
    {
        get => UpdatedBy;
        set => UpdatedBy = value;
    }

    /// <summary>
    /// Issues a new certificate for a completed enrollment.
    /// </summary>
    public static CERTIFICATE Create(Guid enrollmentId, string serialNo, string verifyCode, string? pdfStorageKey, IClock clock)
    {
        ArgumentNullException.ThrowIfNull(clock);

        if (enrollmentId == Guid.Empty)
        {
            throw new ArgumentException("Enrollment ID cannot be empty.", nameof(enrollmentId));
        }

        ArgumentException.ThrowIfNullOrWhiteSpace(serialNo);
        ArgumentException.ThrowIfNullOrWhiteSpace(verifyCode);

        return new CERTIFICATE
        {
            CERTIFICATE_ID = UuidV7.NewId(),
            ENROLLMENT_ID = enrollmentId,
            SERIAL_NO = serialNo.Trim(),
            VERIFY_CODE = verifyCode.Trim(),
            ISSUED_AT_UTC = clock.UtcNow,
            PDF_STORAGE_KEY = pdfStorageKey,
            CreatedAtUtc = clock.UtcNow,
        };
    }

    /// <summary>Invalidates the certificate.</summary>
    public void Revoke(IClock clock)
    {
        ArgumentNullException.ThrowIfNull(clock);

        REVOKED_AT_UTC = clock.UtcNow;
    }
}
